- hosts: localhost
  vars:
      source_key: "./.ssh/id_rsa"
      dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tags: 
    - install
    - core
  tasks:
    - include: ./tasks/ssh.yml
    - include: ./tasks/node-setup.yml
    - include: ./tasks/nvim-setup.yml
    - include: ./tasks/zsh-setup.yml
